### ISSUE TITLE
LVPN Connect - Clicking "Run Browser" runs a private Microsoft Edge browser instance minimised.

### ISSUE THREAD

**Issue by bodane** [letheanVPN/lvpn#10]
OS: Windows (tested and observed only on this OS)

- Microsoft Edge browser opens minimised when clicking Lethean SSH gateway "Run Browser".
- Suspect the expected behavior is to make the launched browser instance windowed or maximised in front of the LVPN app for the expected user experience?

**Comment by limosek** [comment]
Should be fixed.
