### ISSUE TITLE
doc: client-install-dev

### ISSUE THREAD

**Issue by Snider** [letheanVPN/lvpn#12]
![image](https://github.com/letheanVPN/lvpn/assets/631881/493b7b5a-4713-450d-a414-4516360013ca)

Document: https://lethean.space/client-install-dev

## Packages
`apt install python3 python3-pip python3-virtualenv unzip`

On ubuntu you need `python-is-python` for the instructions to work.

## virtualenv paths
Change: `. virtualenv\scripts\activate`
To: `. ./virtualenv/bin/activate`

**Comment by limosek** [comment]
Thank you! Repaired docs
