### ISSUE TITLE
Windows Install Oneliner

### ISSUE THREAD

**Issue by Snider** [letheanVPN/lvpn#14]
Run this in powershell
```powershell
irm https://raw.githubusercontent.com/letheanVPN/lvpn/main/install-all-in-one.ps1 | iex
```

![image](https://github.com/letheanVPN/lvpn/assets/631881/19099655-b2e9-43f9-8dab-2a737b37b590)

**Comment by limosek** [comment]
Thank you! This is nicer solution! :) Will update guide
