### ISSUE TITLE
Post Installation Step

### ISSUE THREAD

**Issue by Snider** [letheanVPN/lvpn#15]
Pretending im a user, not a dev.

I followed the client install guide, which installed fine; what next?

**Comment by limosek** [comment]
If everything went well, you should be able to use HTTP proxy to access .onion sites. 
And your daemon and wallet should become connected and synced over exiting VPN.

You can see "Connections" menu and click "Run browser" button

**Comment by limosek** [comment]
Thank you for pointing this. I know that this button should be bigger and better visible..

**Comment by limosek** [comment]
Updated https://lethean.space/client-install and https://lethean.space/client-manual

**Comment by Snider** [comment]
Looking good.
