### ISSUE TITLE
Doc: curl requests /node-install

### ISSUE THREAD

**Issue by Snider** [letheanVPN/lvpn#18]
The IP's are not exposed.

![image](https://github.com/letheanVPN/lvpn/assets/631881/241bb369-2432-407d-8755-175d482e4484)

https://lethean.space/node-install

**Comment by limosek** [comment]
Thank you for pointing this. I know it is not exposed. We need to solve an security issue here.
For public node, it should never be exposed. For home users with no public IP, it can be exposed.

Will try to update manual for this.

**Comment by limosek** [comment]
Updated https://lethean.space/en/node-install
Is it more clear now?

**Comment by Snider** [comment]
OHHH!!! yes, much better, thanks!
