### ISSUE TITLE
Cannot "Disconnect" then re-connect or "Connect" to the Lethean SSH gateway

### ISSUE THREAD

**Issue by bodane** [letheanVPN/lvpn#3]
OS: Windows (tested and observed only on this OS)

- While in the "Connect" menu, clicking "Disconnect" for Free Lethean SSH gateway does not allow clicking "Connect" again. You must relaunch the application.
- At the moment this may not be such a requirement while in development, however if it were possible it could possibly help as a temporary workaround to issue #1  or #2 .

**Comment by limosek** [comment]
Reworked GUI and now this should work. 
If there are active sessions, you can click to connect. 
If gateway is free and no sessions, you can pay.
After paying, connect is enabled
SSH timeouts should be fixed too.
