### ISSUE TITLE
LVPN can unexpectedly close or hang when clicking between menu items

### ISSUE THREAD

**Issue by bodane** [letheanVPN/lvpn#4]
OS: Windows (tested and observed only on this OS)

- LVPN can unexpectedly close or hang when clicking between menu items.
- General navigation through the menu can close the app.
    - Sometimes the console can show why however have not gathered logs to match up what action may have caused this.
- The app may show the "not responding" message in the window title bar which on occasions recovers, other times it forces the user to close the application due to untimely response from the app.

**Comment by limosek** [comment]
duplicated to #9

**Comment by Snider** [comment]
https://github.com/letheanVPN/lvpn/issues/9#issuecomment-1962462223
