### ISSUE TITLE
python.exe repeatedly attempts connections to localhost TCPv6 port 48782 which is not open.

### ISSUE THREAD

**Issue by bodane** [letheanVPN/lvpn#5]
OS: Windows (tested and observed only on this OS)

- python.exe repeatedly attempts connections to localhost daemon on TCPv6 port 48782 however localhost is not listening on this TCPv6 port.
- TCPv6 connections to localhost are still attempted even when TCPv4 port 48782 session attempts have already succeeded.

**Comment by limosek** [comment]
duplicated to #6
