### ISSUE TITLE
python.exe repeatedly attempts connections to localhost TCPv4 port 1444 after being successfully established.

### ISSUE THREAD

**Issue by bodane** [letheanVPN/lvpn#7]
OS: Windows (tested and observed only on this OS)

- Similar to issue #6 however relating to lethean-wallet-rpc.
- Directly appears to relate to console message `"wallet[7020]:ERROR:HTTPConnectionPool(host='localhost', port=1444): Read timed out. (read timeout=10)"`, does show the session on this port being torn down to localhost lethean-wallet-rpc TCPv4 port 1444.
- This session is established successfully however is torn down after ~10 secs.
- A new session is re-attempted a short while after (within 10-30secs) and the process repeats.
- Have not attempted to use the wallet when in the connected state since the session is brief.

**Comment by limosek** [comment]
These read timeouts are common behaviour of wallet-rpc. Not sure how to deal with this.
When wallet is syncing,  it does not answer for RPC calls. We need to live with this, we just need to nicely explain to users.
Any suggestions how to improve gui for this ?

**Comment by Snider** [comment]
gui issues are out of scope for limo now.
