### ISSUE TITLE
python.exe repeatedly attempts connections to localhost TCPv6 port 1444 which is not open.

### ISSUE THREAD

**Issue by bodane** [letheanVPN/lvpn#8]
OS: Windows (tested and observed only on this OS)

- python.exe repeatedly attempts connections to localhost lethean-wallet-rpc on TCPv6 port 1444 however localhost is not listening on this TCPv6 port.
- TCPv6 connections to localhost are still attempted even when TCPv4 port 1444 session attempts succeed.

**Comment by limosek** [comment]
I think that I have changed this to connect to 127.0.0.1.
Can you recheck please?
