### ISSUE TITLE
LVPN menu items may be unresponsive to a single mouse click, requires a second click.

### ISSUE THREAD

**Issue by bodane** [letheanVPN/lvpn#9]
OS: Windows (tested and observed only on this OS)

- Sometimes you need to click a Menu item twice to enter that menu area.
    - Need to click "Main" button twice to return to main menu.
    - In the "LVPN client home" menu, need to be click twice to enter any menu item.

**Comment by Snider** [comment]
GUI is less of an issue, if we have something that works for development and have a user-facing interface this GUI can be for advanced users/developers.
